variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - lint
  - build

services:
  - docker:dind

pylint:
  image: python:latest
  stage: lint
  script:
    - curl -o .pylintrc https://tool.ix.ai/.pylintrc
    - pip install prometheus_client pylint coinbase
    - pylint --rcfile=.pylintrc *.py

build:
  image: docker:latest
  stage: build
  only:
    - /^latest$/
    - tags
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -f Dockerfile -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}
