variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_REPO_PREFIX: ixdotai
  DOCKERHUB_REPO_NAME: coinbase-exporter

include:
  - remote: https://gitlab.com/ix.ai/ci-templates/raw/master/python-project.yml
